# Generated by Django 4.2.10 on 2024-02-27 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.IntegerField(primary_key=True, serialize=False)),
                ('salutation', models.CharField(choices=[('mr', 'Mr'), ('ms', 'Ms'), ('mrs', 'Mrs')])),
                ('first_name', models.CharField()),
                ('last_name', models.CharField()),
                ('personal_email', models.EmailField(max_length=254)),
                ('full_name', models.CharField()),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField()),
                ('date_of_birth', models.DateField()),
                ('contact_number', models.CharField()),
                ('position', models.CharField(choices=[('solution_analyst', 'Solution Analyst'), ('solution_architect', 'Solution Architect')])),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('read_only', 'Read Only')])),
                ('city', models.CharField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')])),
                ('is_synced', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'employees',
            },
        ),
        migrations.CreateModel(
            name='EmployeeRaw',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('salutation', models.CharField(choices=[('mr', 'Mr'), ('ms', 'Ms'), ('mrs', 'Mrs')])),
                ('first_name', models.CharField()),
                ('last_name', models.CharField()),
                ('personal_email', models.EmailField(max_length=254)),
                ('full_name', models.CharField(null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('password', models.CharField(null=True)),
                ('date_of_birth', models.DateField()),
                ('contact_number', models.CharField()),
                ('position', models.CharField(choices=[('solution_analyst', 'Solution Analyst'), ('solution_architect', 'Solution Architect')])),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('read_only', 'Read Only')])),
                ('city', models.CharField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')])),
                ('is_synced', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'employees_raw',
            },
        ),
    ]
